set commands ""
lappend commands {start 20 100 Hello there this is a test}
lappend commands {set variable $i = -1}
lappend commands "pipe array char*; argv; argc  | if \$i++, \$_output_contains(\"print/s *(char **){}\", \"t\") | show output \$i"
set commands [join $commands "\n"]

run_basic_test "debug filter args" "inferior $debug_inferior\n$commands\n" 0458
wait_for_exit "debug filter args"
# While this command won't work on the non-debug build, it should at least
# provide an error message that is understandable.
run_basic_test "plain filter args" "inferior $plain_inferior\n$commands\n" {No symbol table is loaded.  Use the "file" command.}
wait_for_exit "plain filter args"


unset commands
