set commands ""

set output ""
lappend output "1283169405"
lappend output "89128932"
lappend output "2124247567"
lappend output "1902734705"
lappend output "2141071321"
lappend output "965494256"
lappend output "108111773"
lappend output "850673521"
lappend output "1140597833"

lappend commands "inferior $cpp_inferior"
lappend commands "start 10"
lappend commands "break -function 'create_container<std::__cxx11::list<int, std::allocator<int> >, __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > > >' -label after_defined"
lappend commands "cont"
lappend commands "gdb-pipe pretty-printer rand_container | show print-string *\$cur; \"\\n\""
check_without_reset "Pretty Printer for List can print list elements" commands output

set commands ""
lappend commands "break -function 'create_container<std::vector<int, std::allocator<int> >, __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > > >' -label after_defined"
lappend commands "cont"
lappend commands "gdb-pipe pretty-printer rand_container | show print-string *\$cur; \"\\n\""
check_without_reset "Pretty Printer for Vector can print list elements" commands output

for {set i [expr [llength $output] - 1] } { $i >= 0} {incr i -1} {
  set output [lreplace  $output $i $i "{first = $i, second = [lindex $output $i]}"]
}
set commands ""
lappend commands "break -function 'create_container<std::map<int, int, std::less<int>, std::allocator<std::pair<int const, int> > >, __gnu_cxx::__normal_iterator<std::pair<int, int>*, std::vector<std::pair<int, int>, std::allocator<std::pair<int, int> > > > >' -label after_defined"
lappend commands "cont"
lappend commands "gdb-pipe std-map &rand_container | show print-string *\$cur; \"\\n\""
check_without_reset "Std map walker can find map elements" commands output

set output ""
lappend output "0"
lappend output "1283169405"
lappend output "1"
lappend output "89128932"
lappend output "2"
lappend output "2124247567"
lappend output "3"
lappend output "1902734705"
lappend output "4"
lappend output "2141071321"
lappend output "5"
lappend output "965494256"
lappend output "6"
lappend output "108111773"
lappend output "7"
lappend output "850673521"
lappend output "8"
lappend output "1140597833"
set commands {"gdb-pipe pretty-printer rand_container | show print-string *\$cur; \"\\n\""}
check_without_reset "Pretty Printer for map can print list elements" commands output

ensure_finished "After cpp-structure walker tests"
unset commands
unset output
