send "inferior $debug_inferior\n"
ensure_finished "Before testing tree example"
send "python import demos.tree_walker\ntbreak tree.c:93\nrun 10\n"
set walk "gdb-pipe tree-elements tree_root"
set filter "if {}->children\[0\] == 0 && {}->children\[1\] == 0"
set show "show printf \"\%d\\n\", {}->datum"
run_basic_test "tree walker" "$walk | $filter | $show\n" "1753820418\r\n1255532675\r\n679162307\r\n131589623\r\n" 
wait_for_exit "Finish after tree walker"
unset walk
unset filter
unset show
