# Use separate procedure to ensure no variable clashing
# This does mean we have to access the correct scope with `upvar`
# proc test_shellpipe {} {
set known_calls ""
lappend known_calls "   0x0000000100000b10 <+50>:	callq  0x100000790 <fprintf@plt>"
lappend known_calls "   0x0000000100000b1a <+60>:	callq  0x1000007b0 <exit@plt>"
lappend known_calls "   0x0000000100000b2d <+79>:	callq  0x1000007a0 <atoi@plt>"
lappend known_calls "   0x0000000100000b3a <+92>:	callq  0x100000a53 <create_random_tree>"
lappend known_calls "   0x0000000100000b4a <+108>:	callq  0x1000009e4 <free_tree>"
# # For some reason I don't know, each line is appended with a \r character, so
# # we only add a \n character to each to match the output we're seeing.
set known_calls [join $known_calls "\r\n"]

run_basic_test "shellpipe debug disassemble" "inferior $debug_inferior\nshellpipe disassemble main ! grep call\n" $known_calls
run_basic_test "shellpipe plain disassemble" "inferior $plain_inferior\nshellpipe disassemble main ! grep call\n" $known_calls

unset known_calls
